In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2], dtype=float)

In [3]:
b = a.cumsum()
b

array([0., 1., 3.])

In [4]:
np.diff(b)

array([1., 2.])

In [5]:
np.ediff1d(b, to_begin=b[0])

array([0., 1., 2.])

In [6]:
from empiricaldist import Pmf

In [7]:
import pandas as pd

df = pd.read_csv("lamps.csv")
df.head()

i    h  f   K
0  0    0  0  50
1  1  840  2  48
2  2  852  1  47
3  3  936  1  46
4  4  960  1  45

In [8]:
pmf = Pmf(df.f.values, index=df.h)
pmf.normalize()
pmf.head()

h
0      0.00
840    0.04
852    0.02
936    0.02
960    0.02
dtype: float64

In [9]:
np.sum(pmf)

1.0

In [10]:
pmf.cumsum()[2568]

1.0000000000000002

In [11]:
cdf = pmf.make_cdf()
cdf

h
0       0.00
840     0.04
852     0.06
936     0.08
960     0.10
972     0.12
996     0.14
1008    0.16
1032    0.20
1104    0.22
1176    0.32
1200    0.34
1260    0.36
1296    0.38
1308    0.40
1332    0.44
1356    0.46
1380    0.48
1416    0.50
1476    0.54
1524    0.60
1548    0.66
1560    0.68
1632    0.70
1644    0.74
1656    0.78
1716    0.88
1764    0.90
1812    0.92
1836    0.94
1860    0.96
1980    0.98
2568    1.00
dtype: float64

In [12]:
cdf[2568]

1.0000000000000002

In [13]:
cdf.diff() - pmf

h
0                NaN
840     0.000000e+00
852    -3.469447e-18
936     3.469447e-18
960     3.469447e-18
972     3.469447e-18
996     3.469447e-18
1008   -1.040834e-17
1032    6.938894e-18
1104   -1.040834e-17
1176    0.000000e+00
1200    1.734723e-17
1260    1.734723e-17
1296    1.734723e-17
1308    1.734723e-17
1332   -2.081668e-17
1356    1.734723e-17
1380    1.734723e-17
1416    1.734723e-17
1476    3.469447e-17
1524   -5.551115e-17
1548    5.551115e-17
1560    1.734723e-17
1632    1.734723e-17
1644    3.469447e-17
1656    3.469447e-17
1716   -2.775558e-17
1764    1.734723e-17
1812    1.734723e-17
1836    1.734723e-17
1860    1.734723e-17
1980    1.734723e-17
2568   -9.367507e-17
dtype: float64

In [14]:
from empiricaldist import Surv

p0 = cdf.ps[-1]
p0

1.0000000000000002

In [15]:
surv = Surv(p0-cdf)
surv[0]

1.0000000000000002

In [16]:
surv = cdf.make_surv()
surv

h
0       1.00
840     0.96
852     0.94
936     0.92
960     0.90
972     0.88
996     0.86
1008    0.84
1032    0.80
1104    0.78
1176    0.68
1200    0.66
1260    0.64
1296    0.62
1308    0.60
1332    0.56
1356    0.54
1380    0.52
1416    0.50
1476    0.46
1524    0.40
1548    0.34
1560    0.32
1632    0.30
1644    0.26
1656    0.22
1716    0.12
1764    0.10
1812    0.08
1836    0.06
1860    0.04
1980    0.02
2568    0.00
dtype: float64

In [17]:
surv[0]

1.0

In [18]:
surv.make_cdf()

h
0       0.00
840     0.04
852     0.06
936     0.08
960     0.10
972     0.12
996     0.14
1008    0.16
1032    0.20
1104    0.22
1176    0.32
1200    0.34
1260    0.36
1296    0.38
1308    0.40
1332    0.44
1356    0.46
1380    0.48
1416    0.50
1476    0.54
1524    0.60
1548    0.66
1560    0.68
1632    0.70
1644    0.74
1656    0.78
1716    0.88
1764    0.90
1812    0.92
1836    0.94
1860    0.96
1980    0.98
2568    1.00
dtype: float64

In [19]:
surv.make_pmf()

h
0       0.00
840     0.04
852     0.02
936     0.02
960     0.02
972     0.02
996     0.02
1008    0.02
1032    0.04
1104    0.02
1176    0.10
1200    0.02
1260    0.02
1296    0.02
1308    0.02
1332    0.04
1356    0.02
1380    0.02
1416    0.02
1476    0.04
1524    0.06
1548    0.06
1560    0.02
1632    0.02
1644    0.04
1656    0.04
1716    0.10
1764    0.02
1812    0.02
1836    0.02
1860    0.02
1980    0.02
2568    0.02
dtype: float64