In [1]:
import numpy as np

In [2]:
import pandas as pd

df = pd.read_csv("lamps.csv", index_col=0)
df.head()

h  f   K
i            
0    0  0  50
1  840  2  48
2  852  1  47
3  936  1  46
4  960  1  45

In [3]:
from empiricaldist import Pmf

In [4]:
pmf = Pmf(df.f.values, index=df.h)
pmf.normalize()
pmf.head()

h
0      0.00
840    0.04
852    0.02
936    0.02
960    0.02
dtype: float64

In [5]:
cdf = pmf.make_cdf()
cdf.tail()

h
1812    0.92
1836    0.94
1860    0.96
1980    0.98
2568    1.00
dtype: float64

In [6]:
cdf[2568]

1.0

In [7]:
surv = pmf.make_surv()
surv.head()

h
0      1.00
840    0.96
852    0.94
936    0.92
960    0.90
dtype: float64

In [8]:
surv[0]

1.0

In [9]:
t = [1,2,2,4,5]
pmf = Pmf.from_seq(t, normalize=False)
cdf = pmf.make_cdf()
cdf

1    1
2    3
4    4
5    5
dtype: int64

In [10]:
surv = pmf.make_surv()
surv

1    4
2    2
4    1
5    0
dtype: int64

In [11]:
cdf2 = surv.make_cdf()
cdf2

1    1
2    3
4    4
5    5
dtype: int64

In [12]:
haz = pmf.make_hazard()
list(haz)

[0.2, 0.5, 0.5, 1.0]

In [13]:
pmf2 = haz.make_pmf()
pmf2

1    1.0
2    2.0
4    1.0
5    1.0
dtype: float64

In [14]:
complete = [1,3,6]
ongoing = [2,3,5,7]

pmf_complete = Pmf.from_seq(complete, normalize=False)
pmf_ongoing = Pmf.from_seq(ongoing, normalize=False)

done = pmf_complete + pmf_ongoing
done

1    1.0
2    1.0
3    2.0
5    1.0
6    1.0
7    1.0
dtype: float64

In [15]:
list(pmf_complete - pmf_ongoing)

[1.0, -1.0, 0.0, -1.0, 1.0, -1.0]

In [16]:
list(pmf_complete * pmf_ongoing)

[0.0, 0.0, 1.0, 0.0, 0.0, 0.0]

In [17]:
list(pmf_complete / pmf_ongoing)

[inf, 0.0, 1.0, 0.0, inf, 0.0]

In [18]:
surv_complete = pmf_complete.make_surv()
surv_ongoing = pmf_ongoing.make_surv()

at_risk = pmf_complete + pmf_ongoing
s1 = surv_complete(at_risk.index)
s1

array([2., 2., 1., 1., 0., 0.])

In [19]:
s2 = surv_ongoing(at_risk.index)
s2

array([4., 3., 2., 1., 1., 0.])

In [20]:
at_risk = done + s1 + s2
list(at_risk)

[7.0, 6.0, 5.0, 3.0, 2.0, 1.0]

In [21]:
haz = pmf_complete / at_risk
list(haz)

[0.14285714285714285, 0.0, 0.2, 0.0, 0.5, 0.0]

In [22]:
df = pd.DataFrame(index=haz.index)
df['pmf_complete'] = pmf_complete
df['pmf_ongoing'] = pmf_ongoing
df['surv_complete'] = s1
df['surv_ongoing'] = s2
df['at risk'] = at_risk+s1+s2
df['hazard'] = haz
df

pmf_complete  pmf_ongoing  surv_complete  surv_ongoing  at risk    hazard
1           1.0          NaN            2.0           4.0     13.0  0.142857
2           NaN          1.0            2.0           3.0     11.0  0.000000
3           1.0          1.0            1.0           2.0      8.0  0.200000
5           NaN          1.0            1.0           1.0      5.0  0.000000
6           1.0          NaN            0.0           1.0      3.0  0.500000
7           NaN          1.0            0.0           0.0      1.0  0.000000

In [23]:
from empiricaldist import Surv

t = [1,2,2,3,5]
surv = Surv.from_seq(t, normalize=False)
surv

1    4
2    2
3    1
5    0
dtype: int64

In [24]:
surv([0, 1, 2, 3, 4, 5, 6])

array([5., 4., 2., 1., 1., 0., 0.])

In [25]:
surv.ps

array([4, 2, 1, 0])

In [26]:
surv.qs

array([1, 2, 3, 5])

In [27]:
surv.sort_index()

1    4
2    2
3    1
5    0
dtype: int64

In [28]:
surv.inverse([-1, 0, 1, 2, 3, 4, 5, 6])

array([ nan,   5.,   3.,   2.,   2.,   1., -inf,  nan])

In [29]:
surv = Surv.from_seq(t)
surv

1    0.8
2    0.4
3    0.2
5    0.0
dtype: float64

In [30]:
surv([0, 1, 2, 3, 4, 5, 6])

array([1. , 0.8, 0.4, 0.2, 0.2, 0. , 0. ])

In [31]:
surv.inverse([-0.2, 0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2])

array([ nan,   5.,   3.,   2.,   2.,   1., -inf,  nan])

In [32]:
surv

1    0.8
2    0.4
3    0.2
5    0.0
dtype: float64

In [33]:
t = [1, 2, 2, 3, 5]
pmf = Pmf.from_seq(t, normalize=False)
pmf[0] = 0
pmf.sort_index(inplace=True)
pmf

0    0
1    1
2    2
3    1
5    1
dtype: int64

In [34]:
pmf(4)

0

In [35]:
pmf('a')

0

In [36]:
xs = [0,1,2,3,4,5,6]

In [37]:
pmf(xs)

array([0, 1, 2, 1, 0, 1, 0])

In [38]:
pmf(tuple(xs))

array([0, 1, 2, 1, 0, 1, 0])

In [39]:
pmf(np.array(xs))

array([0, 1, 2, 1, 0, 1, 0])

In [40]:
pmf(pd.Series(xs))

array([0, 1, 2, 1, 0, 1, 0])

In [41]:
cdf = pmf.make_cdf()
cdf

0    0
1    1
2    3
3    4
5    5
dtype: int64

In [42]:
surv = pmf.make_surv()
surv

0    5
1    4
2    2
3    1
5    0
dtype: int64

In [43]:
haz = surv.make_hazard()
haz

0    0.0
1    0.2
2    0.5
3    0.5
5    1.0
dtype: float64

In [44]:
haz(xs)

array([0. , 0.2, 0.5, 0.5, 0. , 1. , 0. ])